### ISSUE TITLE
Videó készítése

### ISSUE THREAD

**Issue by bormilan** [Kalamansanai/portfolio-page#8]
Az lenne a legjobb ha a title page-en egy videó indulna el, amiben megismerheti az oda látogató azt hogy mivel foglalkozunk, amire felkaphatja a fejét, ami ott tartja.

**Comment by bormilan** [comment]
Most a [vmukti oldalát](https://www.vmukti.com/) néztem akkor megtetszett ez a megoldás is amikor vannak képet és azok automatikusan lapozódnak, meg a user is lapozhatja őket.

Illetve az is tetszik, hogy csinálunk egy olyan videót, ami inkább olyan jellegű mintha egy power point lenne felve, szóval ilyen diák/képek egymás után megjelennek és bemutatják hogy kik vagyunk mivel foglalkozunk.

Mit gondoltok ? @Fullbaro @atkalcecpeti @balint-szabox

**Comment by balint-szabox** [comment]
Egyenlőre el lett vetve az ötlet.
